package database;
// Generated 23 ene 2025 14:10:38 by Hibernate Tools 6.5.1.Final

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

	private String idAlumno;
	private Profesor profesor;
	private String nif;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String email;
	private String direccion;
	private Integer codigoPostal;
	private String municipio;
	private String provincia;
	private String beca;

	public Alumno() {
	}

	public Alumno(String idAlumno, String nif, String nombre, String apellido1) {
		this.idAlumno = idAlumno;
		this.nif = nif;
		this.nombre = nombre;
		this.apellido1 = apellido1;
	}

	public Alumno(String idAlumno, Profesor profesor, String nif, String nombre, String apellido1, String apellido2,
			String email, String direccion, Integer codigoPostal, String municipio, String provincia, String beca) {
		this.idAlumno = idAlumno;
		this.profesor = profesor;
		this.nif = nif;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.email = email;
		this.direccion = direccion;
		this.codigoPostal = codigoPostal;
		this.municipio = municipio;
		this.provincia = provincia;
		this.beca = beca;
	}

	public String getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(String idAlumno) {
		this.idAlumno = idAlumno;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Integer getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(Integer codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getBeca() {
		return this.beca;
	}

	public void setBeca(String beca) {
		this.beca = beca;
	}

}
