package database;
// Generated 23 ene 2025 14:10:38 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase implements java.io.Serializable {

	private String codigo;
	private int planta;
	private String materia;
	private Set cursos = new HashSet(0);

	public Clase() {
	}

	public Clase(String codigo, int planta, String materia) {
		this.codigo = codigo;
		this.planta = planta;
		this.materia = materia;
	}

	public Clase(String codigo, int planta, String materia, Set cursos) {
		this.codigo = codigo;
		this.planta = planta;
		this.materia = materia;
		this.cursos = cursos;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public int getPlanta() {
		return this.planta;
	}

	public void setPlanta(int planta) {
		this.planta = planta;
	}

	public String getMateria() {
		return this.materia;
	}

	public void setMateria(String materia) {
		this.materia = materia;
	}

	public Set getCursos() {
		return this.cursos;
	}

	public void setCursos(Set cursos) {
		this.cursos = cursos;
	}

}
