package database;
// Generated 23 ene 2025 14:10:38 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private int idCurso;
	private String nombreDescriptivo;
	private int nasignaturas;
	private Set clases = new HashSet(0);

	public Curso() {
	}

	public Curso(int idCurso, String nombreDescriptivo, int nasignaturas) {
		this.idCurso = idCurso;
		this.nombreDescriptivo = nombreDescriptivo;
		this.nasignaturas = nasignaturas;
	}

	public Curso(int idCurso, String nombreDescriptivo, int nasignaturas, Set clases) {
		this.idCurso = idCurso;
		this.nombreDescriptivo = nombreDescriptivo;
		this.nasignaturas = nasignaturas;
		this.clases = clases;
	}

	public int getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(int idCurso) {
		this.idCurso = idCurso;
	}

	public String getNombreDescriptivo() {
		return this.nombreDescriptivo;
	}

	public void setNombreDescriptivo(String nombreDescriptivo) {
		this.nombreDescriptivo = nombreDescriptivo;
	}

	public int getNasignaturas() {
		return this.nasignaturas;
	}

	public void setNasignaturas(int nasignaturas) {
		this.nasignaturas = nasignaturas;
	}

	public Set getClases() {
		return this.clases;
	}

	public void setClases(Set clases) {
		this.clases = clases;
	}

}
