package database;
// Generated 23 ene 2025 14:10:38 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private String idProfesor;
	private String nombre;
	private Set alumnos = new HashSet(0);

	public Profesor() {
	}

	public Profesor(String idProfesor, String nombre) {
		this.idProfesor = idProfesor;
		this.nombre = nombre;
	}

	public Profesor(String idProfesor, String nombre, Set alumnos) {
		this.idProfesor = idProfesor;
		this.nombre = nombre;
		this.alumnos = alumnos;
	}

	public String getIdProfesor() {
		return this.idProfesor;
	}

	public void setIdProfesor(String idProfesor) {
		this.idProfesor = idProfesor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set alumnos) {
		this.alumnos = alumnos;
	}

}
